In [20]:
import numpy as np

**72. How to swap two rows of an array?** 

In [21]:
arr=np.arange(24).reshape(4,6)
print("Original array:\n******************")
print(arr)
for i in range(1,3):
    arr[[0, i],:] = arr[[i, 0],:]

print("\nAfter swapping arrays:\n************")
print(arr)

Original array:
******************
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

After swapping arrays:
************
[[12 13 14 15 16 17]
 [ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [18 19 20 21 22 23]]


**75. How to compute averages using a sliding window over an array?**