In [1]:
import numpy as np


**34. How to get all the dates corresponding to the month of July 2016**

In [35]:

print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


**42. Consider two random array A and B, check if they are equal**

In [32]:
arr_A=np.random.randint(10,size=(3,3))
print(arr_A)
arr_B=np.random.randint(15,size=(3,3))
print(arr_B)
comparsion=arr_A.all()==arr_B.all()
check_arr=comparsion.all()
if check_arr:
    print("The arrys are equal!")
else:
    print("The arrays are not equal!")


[[1 7 3]
 [1 2 2]
 [1 6 3]]
[[ 9  3  6]
 [ 5 14 11]
 [14  2  5]]
The arrys are equal!
